# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T10:57:52+00:00



import argparse
import json
import os
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity, HTTPBasic
from fastapi import Header, Path, Query
from pydantic import conint, constr
from starlette.requests import Request

from models import (
    BindingType,
    ConversationEnumState,
    ConversationEnumWebhookEnabledType,
    ConversationMessageEnumOrderType,
    ConversationMessageEnumWebhookEnabledType,
    ConversationParticipantEnumWebhookEnabledType,
    ConversationsV1Configuration,
    ConversationsV1ConfigurationAddress,
    ConversationsV1ConfigurationConfigurationWebhook,
    ConversationsV1Conversation,
    ConversationsV1ConversationConversationMessage,
    ConversationsV1ConversationConversationMessageConversationMessageReceipt,
    ConversationsV1ConversationConversationParticipant,
    ConversationsV1ConversationConversationScopedWebhook,
    ConversationsV1Credential,
    ConversationsV1Role,
    ConversationsV1Service,
    ConversationsV1ServiceServiceBinding,
    ConversationsV1ServiceServiceConfiguration,
    ConversationsV1ServiceServiceConfigurationServiceNotification,
    ConversationsV1ServiceServiceConfigurationServiceWebhookConfiguration,
    ConversationsV1ServiceServiceConversation,
    ConversationsV1ServiceServiceConversationServiceConversationMessage,
    ConversationsV1ServiceServiceConversationServiceConversationMessageServiceConversationMessageReceipt,
    ConversationsV1ServiceServiceConversationServiceConversationParticipant,
    ConversationsV1ServiceServiceConversationServiceConversationScopedWebhook,
    ConversationsV1ServiceServiceRole,
    ConversationsV1ServiceServiceUser,
    ConversationsV1ServiceServiceUserServiceUserConversation,
    ConversationsV1User,
    ConversationsV1UserUserConversation,
    Identity,
    ServiceConversationEnumState,
    ServiceConversationEnumWebhookEnabledType,
    ServiceConversationMessageEnumOrderType,
    ServiceConversationMessageEnumWebhookEnabledType,
    ServiceConversationParticipantEnumWebhookEnabledType,
    ServiceUserEnumWebhookEnabledType,
    UserEnumWebhookEnabledType,
    V1ConfigurationAddressesGetResponse,
    V1ConversationsConversationSidMessagesGetResponse,
    V1ConversationsConversationSidMessagesMessageSidReceiptsGetResponse,
    V1ConversationsConversationSidParticipantsGetResponse,
    V1ConversationsConversationSidWebhooksGetResponse,
    V1ConversationsGetResponse,
    V1CredentialsGetResponse,
    V1ParticipantConversationsGetResponse,
    V1RolesGetResponse,
    V1ServicesChatServiceSidBindingsGetResponse,
    V1ServicesChatServiceSidConversationsConversationSidMessagesGetResponse,
    V1ServicesChatServiceSidConversationsConversationSidMessagesMessageSidReceiptsGetResponse,
    V1ServicesChatServiceSidConversationsConversationSidParticipantsGetResponse,
    V1ServicesChatServiceSidConversationsConversationSidWebhooksGetResponse,
    V1ServicesChatServiceSidConversationsGetResponse,
    V1ServicesChatServiceSidParticipantConversationsGetResponse,
    V1ServicesChatServiceSidRolesGetResponse,
    V1ServicesChatServiceSidUsersGetResponse,
    V1ServicesChatServiceSidUsersUserSidConversationsGetResponse,
    V1ServicesGetResponse,
    V1UsersGetResponse,
    V1UsersUserSidConversationsGetResponse,
)

app = MCPProxy(
    contact={
        'email': 'support@twilio.com',
        'name': 'Twilio Support',
        'url': 'https://support.twilio.com',
    },
    description='This is the public Twilio REST API.',
    license={
        'name': 'Apache 2.0',
        'url': 'https://www.apache.org/licenses/LICENSE-2.0.html',
    },
    termsOfService='https://www.twilio.com/legal/tos',
    title='Twilio - Conversations',
    version='1.42.0',
    servers=[{'url': 'https://conversations.twilio.com'}],
)


@app.get(
    '/v1/Configuration',
    description=""" Fetch the global configuration of conversations on your account """,
    tags=['configuration_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_configuration():
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Configuration',
    description=""" Update the global configuration of conversations on your account """,
    tags=['service_configuration'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def update_configuration(request: Request):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Configuration/Addresses',
    description=""" Retrieve a list of address configurations for an account """,
    tags=['service_configuration'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def list_configuration_address(
    type: Optional[str] = Query(None, alias='Type'),
    page_size: Optional[conint(ge=1, le=1000)] = Query(None, alias='PageSize'),
    page: Optional[conint(ge=0)] = Query(None, alias='Page'),
    page_token: Optional[str] = Query(None, alias='PageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Configuration/Addresses',
    description=""" Create a new address configuration """,
    tags=['configuration_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def create_configuration_address(request: Request):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/v1/Configuration/Addresses/{Sid}',
    description=""" Remove an existing address configuration """,
    tags=['user_account_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def delete_configuration_address(sid: str = Path(..., alias='Sid')):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Configuration/Addresses/{Sid}',
    description=""" Fetch an address configuration  """,
    tags=['user_conversation_relationship'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_configuration_address(sid: str = Path(..., alias='Sid')):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Configuration/Addresses/{Sid}',
    description=""" Update an existing address configuration """,
    tags=['user_conversation_relationship'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def update_configuration_address(
    sid: str = Path(..., alias='Sid'), request: Request = ...
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Configuration/Webhooks',
    tags=['service_configuration'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_configuration_webhook():
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Configuration/Webhooks',
    tags=[
        'configuration_management',
        'conversation_management',
        'credential_handling',
        'role_configuration',
        'service_configuration',
        'message_operations',
        'service_binding_operations',
        'conversation_message_management',
        'participant_management',
        'scoped_webhook_operations',
        'user_account_management',
        'user_conversation_relationship',
    ],
    security=[
        HTTPBasic(name="None"),
    ],
)
def update_configuration_webhook(request: Request):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Conversations',
    description=""" Retrieve a list of conversations in your account's default service """,
    tags=['conversation_management', 'user_conversation_relationship'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def list_conversation(
    start_date: Optional[str] = Query(None, alias='StartDate'),
    end_date: Optional[str] = Query(None, alias='EndDate'),
    state: Optional[ConversationEnumState] = Query(None, alias='State'),
    page_size: Optional[conint(ge=1, le=1000)] = Query(None, alias='PageSize'),
    page: Optional[conint(ge=0)] = Query(None, alias='Page'),
    page_token: Optional[str] = Query(None, alias='PageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Conversations',
    description=""" Create a new conversation in your account's default service """,
    tags=['configuration_management', 'scoped_webhook_operations'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def create_conversation(
    x__twilio__webhook__enabled: Optional[ConversationEnumWebhookEnabledType] = Header(
        None, alias='X-Twilio-Webhook-Enabled'
    ),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Conversations/{ConversationSid}/Messages',
    description=""" Retrieve a list of all messages in the conversation """,
    tags=['conversation_management', 'conversation_message_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def list_conversation_message(
    conversation_sid: str = Path(..., alias='ConversationSid'),
    order: Optional[ConversationMessageEnumOrderType] = Query(None, alias='Order'),
    page_size: Optional[conint(ge=1, le=1000)] = Query(None, alias='PageSize'),
    page: Optional[conint(ge=0)] = Query(None, alias='Page'),
    page_token: Optional[str] = Query(None, alias='PageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Conversations/{ConversationSid}/Messages',
    description=""" Add a new message to the conversation """,
    tags=['conversation_management', 'scoped_webhook_operations'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def create_conversation_message(
    conversation_sid: str = Path(..., alias='ConversationSid'),
    x__twilio__webhook__enabled: Optional[
        ConversationMessageEnumWebhookEnabledType
    ] = Header(None, alias='X-Twilio-Webhook-Enabled'),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Conversations/{ConversationSid}/Messages/{MessageSid}/Receipts',
    description=""" Retrieve a list of all delivery and read receipts of the conversation message """,
    tags=[
        'conversation_management',
        'conversation_message_management',
        'message_operations',
    ],
    security=[
        HTTPBasic(name="None"),
    ],
)
def list_conversation_message_receipt(
    conversation_sid: str = Path(..., alias='ConversationSid'),
    message_sid: constr(
        pattern=r'^IM[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='MessageSid'),
    page_size: Optional[conint(ge=1, le=1000)] = Query(None, alias='PageSize'),
    page: Optional[conint(ge=0)] = Query(None, alias='Page'),
    page_token: Optional[str] = Query(None, alias='PageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Conversations/{ConversationSid}/Messages/{MessageSid}/Receipts/{Sid}',
    description=""" Fetch the delivery and read receipts of the conversation message """,
    tags=[
        'conversation_management',
        'conversation_message_management',
        'message_operations',
    ],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_conversation_message_receipt(
    conversation_sid: str = Path(..., alias='ConversationSid'),
    message_sid: constr(
        pattern=r'^IM[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='MessageSid'),
    sid: constr(pattern=r'^DY[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/v1/Conversations/{ConversationSid}/Messages/{Sid}',
    description=""" Remove a message from the conversation """,
    tags=[
        'conversation_management',
        'conversation_message_management',
        'scoped_webhook_operations',
    ],
    security=[
        HTTPBasic(name="None"),
    ],
)
def delete_conversation_message(
    conversation_sid: str = Path(..., alias='ConversationSid'),
    sid: constr(pattern=r'^IM[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
    x__twilio__webhook__enabled: Optional[
        ConversationMessageEnumWebhookEnabledType
    ] = Header(None, alias='X-Twilio-Webhook-Enabled'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Conversations/{ConversationSid}/Messages/{Sid}',
    description=""" Fetch a message from the conversation """,
    tags=['conversation_management', 'participant_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_conversation_message(
    conversation_sid: str = Path(..., alias='ConversationSid'),
    sid: constr(pattern=r'^IM[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Conversations/{ConversationSid}/Messages/{Sid}',
    description=""" Update an existing message in the conversation """,
    tags=[
        'conversation_management',
        'conversation_message_management',
        'scoped_webhook_operations',
    ],
    security=[
        HTTPBasic(name="None"),
    ],
)
def update_conversation_message(
    conversation_sid: str = Path(..., alias='ConversationSid'),
    sid: constr(pattern=r'^IM[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
    x__twilio__webhook__enabled: Optional[
        ConversationMessageEnumWebhookEnabledType
    ] = Header(None, alias='X-Twilio-Webhook-Enabled'),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Conversations/{ConversationSid}/Participants',
    description=""" Retrieve a list of all participants of the conversation """,
    tags=['conversation_management', 'participant_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def list_conversation_participant(
    conversation_sid: str = Path(..., alias='ConversationSid'),
    page_size: Optional[conint(ge=1, le=1000)] = Query(None, alias='PageSize'),
    page: Optional[conint(ge=0)] = Query(None, alias='Page'),
    page_token: Optional[str] = Query(None, alias='PageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Conversations/{ConversationSid}/Participants',
    description=""" Add a new participant to the conversation """,
    tags=[
        'conversation_management',
        'participant_management',
        'scoped_webhook_operations',
    ],
    security=[
        HTTPBasic(name="None"),
    ],
)
def create_conversation_participant(
    conversation_sid: str = Path(..., alias='ConversationSid'),
    x__twilio__webhook__enabled: Optional[
        ConversationParticipantEnumWebhookEnabledType
    ] = Header(None, alias='X-Twilio-Webhook-Enabled'),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/v1/Conversations/{ConversationSid}/Participants/{Sid}',
    description=""" Remove a participant from the conversation """,
    tags=['participant_management', 'scoped_webhook_operations'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def delete_conversation_participant(
    conversation_sid: str = Path(..., alias='ConversationSid'),
    sid: str = Path(..., alias='Sid'),
    x__twilio__webhook__enabled: Optional[
        ConversationParticipantEnumWebhookEnabledType
    ] = Header(None, alias='X-Twilio-Webhook-Enabled'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Conversations/{ConversationSid}/Participants/{Sid}',
    description=""" Fetch a participant of the conversation """,
    tags=[
        'conversation_management',
        'participant_management',
        'user_conversation_relationship',
    ],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_conversation_participant(
    conversation_sid: str = Path(..., alias='ConversationSid'),
    sid: str = Path(..., alias='Sid'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Conversations/{ConversationSid}/Participants/{Sid}',
    description=""" Update an existing participant in the conversation """,
    tags=[
        'conversation_management',
        'participant_management',
        'scoped_webhook_operations',
    ],
    security=[
        HTTPBasic(name="None"),
    ],
)
def update_conversation_participant(
    conversation_sid: str = Path(..., alias='ConversationSid'),
    sid: str = Path(..., alias='Sid'),
    x__twilio__webhook__enabled: Optional[
        ConversationParticipantEnumWebhookEnabledType
    ] = Header(None, alias='X-Twilio-Webhook-Enabled'),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Conversations/{ConversationSid}/Webhooks',
    description=""" Retrieve a list of all webhooks scoped to the conversation """,
    tags=[
        'conversation_management',
        'participant_management',
        'user_conversation_relationship',
    ],
    security=[
        HTTPBasic(name="None"),
    ],
)
def list_conversation_scoped_webhook(
    conversation_sid: str = Path(..., alias='ConversationSid'),
    page_size: Optional[conint(ge=1, le=1000)] = Query(None, alias='PageSize'),
    page: Optional[conint(ge=0)] = Query(None, alias='Page'),
    page_token: Optional[str] = Query(None, alias='PageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Conversations/{ConversationSid}/Webhooks',
    description=""" Create a new webhook scoped to the conversation """,
    tags=['conversation_management', 'participant_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def create_conversation_scoped_webhook(
    conversation_sid: str = Path(..., alias='ConversationSid'), request: Request = ...
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/v1/Conversations/{ConversationSid}/Webhooks/{Sid}',
    description=""" Remove an existing webhook scoped to the conversation """,
    tags=['conversation_management', 'participant_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def delete_conversation_scoped_webhook(
    conversation_sid: str = Path(..., alias='ConversationSid'),
    sid: constr(pattern=r'^WH[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Conversations/{ConversationSid}/Webhooks/{Sid}',
    description=""" Fetch the configuration of a conversation-scoped webhook """,
    tags=['conversation_management', 'participant_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_conversation_scoped_webhook(
    conversation_sid: str = Path(..., alias='ConversationSid'),
    sid: constr(pattern=r'^WH[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Conversations/{ConversationSid}/Webhooks/{Sid}',
    description=""" Update an existing conversation-scoped webhook """,
    tags=['conversation_management', 'participant_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def update_conversation_scoped_webhook(
    conversation_sid: str = Path(..., alias='ConversationSid'),
    sid: constr(pattern=r'^WH[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/v1/Conversations/{Sid}',
    description=""" Remove a conversation from your account's default service """,
    tags=['configuration_management', 'scoped_webhook_operations'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def delete_conversation(
    sid: str = Path(..., alias='Sid'),
    x__twilio__webhook__enabled: Optional[ConversationEnumWebhookEnabledType] = Header(
        None, alias='X-Twilio-Webhook-Enabled'
    ),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Conversations/{Sid}',
    description=""" Fetch a conversation from your account's default service """,
    tags=['user_account_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_conversation(sid: str = Path(..., alias='Sid')):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Conversations/{Sid}',
    description=""" Update an existing conversation in your account's default service """,
    tags=['configuration_management', 'scoped_webhook_operations'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def update_conversation(
    sid: str = Path(..., alias='Sid'),
    x__twilio__webhook__enabled: Optional[ConversationEnumWebhookEnabledType] = Header(
        None, alias='X-Twilio-Webhook-Enabled'
    ),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Credentials',
    description=""" Retrieve a list of all push notification credentials on your account """,
    tags=['configuration_management', 'user_account_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def list_credential(
    page_size: Optional[conint(ge=1, le=1000)] = Query(None, alias='PageSize'),
    page: Optional[conint(ge=0)] = Query(None, alias='Page'),
    page_token: Optional[str] = Query(None, alias='PageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Credentials',
    description=""" Add a new push notification credential to your account """,
    tags=['configuration_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def create_credential(request: Request):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/v1/Credentials/{Sid}',
    description=""" Remove a push notification credential from your account """,
    tags=['configuration_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def delete_credential(
    sid: constr(pattern=r'^CR[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    )
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Credentials/{Sid}',
    description=""" Fetch a push notification credential from your account """,
    tags=['user_account_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_credential(
    sid: constr(pattern=r'^CR[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    )
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Credentials/{Sid}',
    description=""" Update an existing push notification credential on your account """,
    tags=['credential_handling'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def update_credential(
    sid: constr(pattern=r'^CR[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/ParticipantConversations',
    description=""" Retrieve a list of all Conversations that this Participant belongs to by identity or by address. Only one parameter should be specified. """,
    tags=['user_conversation_relationship'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def list_participant_conversation(
    identity: Optional[str] = Query(None, alias='Identity'),
    address: Optional[str] = Query(None, alias='Address'),
    page_size: Optional[conint(ge=1, le=1000)] = Query(None, alias='PageSize'),
    page: Optional[conint(ge=0)] = Query(None, alias='Page'),
    page_token: Optional[str] = Query(None, alias='PageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Roles',
    description=""" Retrieve a list of all user roles in your account's default service """,
    tags=['conversation_management', 'user_conversation_relationship'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def list_role(
    page_size: Optional[conint(ge=1, le=1000)] = Query(None, alias='PageSize'),
    page: Optional[conint(ge=0)] = Query(None, alias='Page'),
    page_token: Optional[str] = Query(None, alias='PageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Roles',
    description=""" Create a new user role in your account's default service """,
    tags=['user_account_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def create_role(request: Request):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/v1/Roles/{Sid}',
    description=""" Remove a user role from your account's default service """,
    tags=['role_configuration'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def delete_role(
    sid: constr(pattern=r'^RL[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    )
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Roles/{Sid}',
    description=""" Fetch a user role from your account's default service """,
    tags=['configuration_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_role(
    sid: constr(pattern=r'^RL[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    )
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Roles/{Sid}',
    description=""" Update an existing user role in your account's default service """,
    tags=['service_configuration'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def update_role(
    sid: constr(pattern=r'^RL[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Services',
    description=""" Retrieve a list of all conversation services on your account """,
    tags=['configuration_management', 'service_configuration'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def list_service(
    page_size: Optional[conint(ge=1, le=1000)] = Query(None, alias='PageSize'),
    page: Optional[conint(ge=0)] = Query(None, alias='Page'),
    page_token: Optional[str] = Query(None, alias='PageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Services',
    description=""" Create a new conversation service on your account """,
    tags=['configuration_management', 'conversation_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def create_service(request: Request):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Services/{ChatServiceSid}/Bindings',
    description=""" Retrieve a list of all push notification bindings in the conversation service """,
    tags=['service_binding_operations'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def list_service_binding(
    chat_service_sid: constr(
        pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='ChatServiceSid'),
    binding_type: Optional[BindingType] = Query(None, alias='BindingType'),
    identity: Optional[Identity] = Query(None, alias='Identity'),
    page_size: Optional[conint(ge=1, le=1000)] = Query(None, alias='PageSize'),
    page: Optional[conint(ge=0)] = Query(None, alias='Page'),
    page_token: Optional[str] = Query(None, alias='PageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/v1/Services/{ChatServiceSid}/Bindings/{Sid}',
    description=""" Remove a push notification binding from the conversation service """,
    tags=['service_configuration', 'conversation_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def delete_service_binding(
    chat_service_sid: constr(
        pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='ChatServiceSid'),
    sid: constr(pattern=r'^BS[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Services/{ChatServiceSid}/Bindings/{Sid}',
    description=""" Fetch a push notification binding from the conversation service """,
    tags=['conversation_management', 'participant_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_service_binding(
    chat_service_sid: constr(
        pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='ChatServiceSid'),
    sid: constr(pattern=r'^BS[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Services/{ChatServiceSid}/Configuration',
    description=""" Fetch the configuration of a conversation service """,
    tags=['service_configuration'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_service_configuration(
    chat_service_sid: constr(
        pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='ChatServiceSid')
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Services/{ChatServiceSid}/Configuration',
    description=""" Update configuration settings of a conversation service """,
    tags=['conversation_management', 'user_conversation_relationship'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def update_service_configuration(
    chat_service_sid: constr(
        pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='ChatServiceSid'),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Services/{ChatServiceSid}/Configuration/Notifications',
    description=""" Fetch push notification service settings """,
    tags=['conversation_management', 'participant_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_service_notification(
    chat_service_sid: constr(
        pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='ChatServiceSid')
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Services/{ChatServiceSid}/Configuration/Notifications',
    description=""" Update push notification service settings """,
    tags=['conversation_management', 'user_conversation_relationship'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def update_service_notification(
    chat_service_sid: constr(
        pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='ChatServiceSid'),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Services/{ChatServiceSid}/Configuration/Webhooks',
    description=""" Fetch a specific service webhook configuration. """,
    tags=['service_configuration'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_service_webhook_configuration(
    chat_service_sid: constr(
        pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='ChatServiceSid')
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Services/{ChatServiceSid}/Configuration/Webhooks',
    description=""" Update a specific Webhook. """,
    tags=['service_configuration', 'conversation_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def update_service_webhook_configuration(
    chat_service_sid: constr(
        pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='ChatServiceSid'),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Services/{ChatServiceSid}/Conversations',
    description=""" Retrieve a list of conversations in your service """,
    tags=['conversation_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def list_service_conversation(
    chat_service_sid: constr(
        pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='ChatServiceSid'),
    start_date: Optional[str] = Query(None, alias='StartDate'),
    end_date: Optional[str] = Query(None, alias='EndDate'),
    state: Optional[ServiceConversationEnumState] = Query(None, alias='State'),
    page_size: Optional[conint(ge=1, le=1000)] = Query(None, alias='PageSize'),
    page: Optional[conint(ge=0)] = Query(None, alias='Page'),
    page_token: Optional[str] = Query(None, alias='PageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Services/{ChatServiceSid}/Conversations',
    description=""" Create a new conversation in your service """,
    tags=[
        'configuration_management',
        'service_configuration',
        'scoped_webhook_operations',
    ],
    security=[
        HTTPBasic(name="None"),
    ],
)
def create_service_conversation(
    chat_service_sid: constr(
        pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='ChatServiceSid'),
    x__twilio__webhook__enabled: Optional[
        ServiceConversationEnumWebhookEnabledType
    ] = Header(None, alias='X-Twilio-Webhook-Enabled'),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Services/{ChatServiceSid}/Conversations/{ConversationSid}/Messages',
    description=""" Retrieve a list of all messages in the conversation """,
    tags=['conversation_management', 'conversation_message_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def list_service_conversation_message(
    chat_service_sid: constr(
        pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='ChatServiceSid'),
    conversation_sid: str = Path(..., alias='ConversationSid'),
    order: Optional[ServiceConversationMessageEnumOrderType] = Query(
        None, alias='Order'
    ),
    page_size: Optional[conint(ge=1, le=1000)] = Query(None, alias='PageSize'),
    page: Optional[conint(ge=0)] = Query(None, alias='Page'),
    page_token: Optional[str] = Query(None, alias='PageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Services/{ChatServiceSid}/Conversations/{ConversationSid}/Messages',
    description=""" Add a new message to the conversation in a specific service """,
    tags=['conversation_management', 'scoped_webhook_operations', 'message_operations'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def create_service_conversation_message(
    chat_service_sid: constr(
        pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='ChatServiceSid'),
    conversation_sid: str = Path(..., alias='ConversationSid'),
    x__twilio__webhook__enabled: Optional[
        ServiceConversationMessageEnumWebhookEnabledType
    ] = Header(None, alias='X-Twilio-Webhook-Enabled'),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Services/{ChatServiceSid}/Conversations/{ConversationSid}/Messages/{MessageSid}/Receipts',
    description=""" Retrieve a list of all delivery and read receipts of the conversation message """,
    tags=['conversation_message_management', 'message_operations'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def list_service_conversation_message_receipt(
    chat_service_sid: constr(
        pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='ChatServiceSid'),
    conversation_sid: str = Path(..., alias='ConversationSid'),
    message_sid: constr(
        pattern=r'^IM[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='MessageSid'),
    page_size: Optional[conint(ge=1, le=1000)] = Query(None, alias='PageSize'),
    page: Optional[conint(ge=0)] = Query(None, alias='Page'),
    page_token: Optional[str] = Query(None, alias='PageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Services/{ChatServiceSid}/Conversations/{ConversationSid}/Messages/{MessageSid}/Receipts/{Sid}',
    description=""" Fetch the delivery and read receipts of the conversation message """,
    tags=['conversation_message_management', 'message_operations'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_service_conversation_message_receipt(
    chat_service_sid: constr(
        pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='ChatServiceSid'),
    conversation_sid: str = Path(..., alias='ConversationSid'),
    message_sid: constr(
        pattern=r'^IM[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='MessageSid'),
    sid: constr(pattern=r'^DY[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/v1/Services/{ChatServiceSid}/Conversations/{ConversationSid}/Messages/{Sid}',
    description=""" Remove a message from the conversation """,
    tags=[
        'conversation_management',
        'conversation_message_management',
        'scoped_webhook_operations',
    ],
    security=[
        HTTPBasic(name="None"),
    ],
)
def delete_service_conversation_message(
    chat_service_sid: constr(
        pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='ChatServiceSid'),
    conversation_sid: str = Path(..., alias='ConversationSid'),
    sid: constr(pattern=r'^IM[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
    x__twilio__webhook__enabled: Optional[
        ServiceConversationMessageEnumWebhookEnabledType
    ] = Header(None, alias='X-Twilio-Webhook-Enabled'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Services/{ChatServiceSid}/Conversations/{ConversationSid}/Messages/{Sid}',
    description=""" Fetch a message from the conversation """,
    tags=['conversation_management', 'participant_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_service_conversation_message(
    chat_service_sid: constr(
        pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='ChatServiceSid'),
    conversation_sid: str = Path(..., alias='ConversationSid'),
    sid: constr(pattern=r'^IM[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Services/{ChatServiceSid}/Conversations/{ConversationSid}/Messages/{Sid}',
    description=""" Update an existing message in the conversation """,
    tags=[
        'conversation_management',
        'message_operations',
        'conversation_message_management',
    ],
    security=[
        HTTPBasic(name="None"),
    ],
)
def update_service_conversation_message(
    chat_service_sid: constr(
        pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='ChatServiceSid'),
    conversation_sid: str = Path(..., alias='ConversationSid'),
    sid: constr(pattern=r'^IM[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
    x__twilio__webhook__enabled: Optional[
        ServiceConversationMessageEnumWebhookEnabledType
    ] = Header(None, alias='X-Twilio-Webhook-Enabled'),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Services/{ChatServiceSid}/Conversations/{ConversationSid}/Participants',
    description=""" Retrieve a list of all participants of the conversation """,
    tags=[
        'conversation_management',
        'conversation_message_management',
        'participant_management',
    ],
    security=[
        HTTPBasic(name="None"),
    ],
)
def list_service_conversation_participant(
    chat_service_sid: constr(
        pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='ChatServiceSid'),
    conversation_sid: str = Path(..., alias='ConversationSid'),
    page_size: Optional[conint(ge=1, le=1000)] = Query(None, alias='PageSize'),
    page: Optional[conint(ge=0)] = Query(None, alias='Page'),
    page_token: Optional[str] = Query(None, alias='PageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Services/{ChatServiceSid}/Conversations/{ConversationSid}/Participants',
    description=""" Add a new participant to the conversation in a specific service """,
    tags=[
        'conversation_management',
        'scoped_webhook_operations',
        'participant_management',
    ],
    security=[
        HTTPBasic(name="None"),
    ],
)
def create_service_conversation_participant(
    chat_service_sid: constr(
        pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='ChatServiceSid'),
    conversation_sid: str = Path(..., alias='ConversationSid'),
    x__twilio__webhook__enabled: Optional[
        ServiceConversationParticipantEnumWebhookEnabledType
    ] = Header(None, alias='X-Twilio-Webhook-Enabled'),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/v1/Services/{ChatServiceSid}/Conversations/{ConversationSid}/Participants/{Sid}',
    description=""" Remove a participant from the conversation """,
    tags=[
        'participant_management',
        'conversation_management',
        'scoped_webhook_operations',
    ],
    security=[
        HTTPBasic(name="None"),
    ],
)
def delete_service_conversation_participant(
    chat_service_sid: constr(
        pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='ChatServiceSid'),
    conversation_sid: str = Path(..., alias='ConversationSid'),
    sid: str = Path(..., alias='Sid'),
    x__twilio__webhook__enabled: Optional[
        ServiceConversationParticipantEnumWebhookEnabledType
    ] = Header(None, alias='X-Twilio-Webhook-Enabled'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Services/{ChatServiceSid}/Conversations/{ConversationSid}/Participants/{Sid}',
    description=""" Fetch a participant of the conversation """,
    tags=['conversation_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_service_conversation_participant(
    chat_service_sid: constr(
        pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='ChatServiceSid'),
    conversation_sid: str = Path(..., alias='ConversationSid'),
    sid: str = Path(..., alias='Sid'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Services/{ChatServiceSid}/Conversations/{ConversationSid}/Participants/{Sid}',
    description=""" Update an existing participant in the conversation """,
    tags=[
        'conversation_management',
        'participant_management',
        'scoped_webhook_operations',
    ],
    security=[
        HTTPBasic(name="None"),
    ],
)
def update_service_conversation_participant(
    chat_service_sid: constr(
        pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='ChatServiceSid'),
    conversation_sid: str = Path(..., alias='ConversationSid'),
    sid: str = Path(..., alias='Sid'),
    x__twilio__webhook__enabled: Optional[
        ServiceConversationParticipantEnumWebhookEnabledType
    ] = Header(None, alias='X-Twilio-Webhook-Enabled'),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Services/{ChatServiceSid}/Conversations/{ConversationSid}/Webhooks',
    description=""" Retrieve a list of all webhooks scoped to the conversation """,
    tags=['conversation_management', 'conversation_message_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def list_service_conversation_scoped_webhook(
    chat_service_sid: constr(
        pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='ChatServiceSid'),
    conversation_sid: str = Path(..., alias='ConversationSid'),
    page_size: Optional[conint(ge=1, le=1000)] = Query(None, alias='PageSize'),
    page: Optional[conint(ge=0)] = Query(None, alias='Page'),
    page_token: Optional[str] = Query(None, alias='PageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Services/{ChatServiceSid}/Conversations/{ConversationSid}/Webhooks',
    description=""" Create a new webhook scoped to the conversation in a specific service """,
    tags=[
        'conversation_management',
        'conversation_message_management',
        'participant_management',
    ],
    security=[
        HTTPBasic(name="None"),
    ],
)
def create_service_conversation_scoped_webhook(
    chat_service_sid: constr(
        pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='ChatServiceSid'),
    conversation_sid: str = Path(..., alias='ConversationSid'),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/v1/Services/{ChatServiceSid}/Conversations/{ConversationSid}/Webhooks/{Sid}',
    description=""" Remove an existing webhook scoped to the conversation """,
    tags=['conversation_management', 'participant_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def delete_service_conversation_scoped_webhook(
    chat_service_sid: constr(
        pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='ChatServiceSid'),
    conversation_sid: str = Path(..., alias='ConversationSid'),
    sid: constr(pattern=r'^WH[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Services/{ChatServiceSid}/Conversations/{ConversationSid}/Webhooks/{Sid}',
    description=""" Fetch the configuration of a conversation-scoped webhook """,
    tags=['conversation_management', 'participant_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_service_conversation_scoped_webhook(
    chat_service_sid: constr(
        pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='ChatServiceSid'),
    conversation_sid: str = Path(..., alias='ConversationSid'),
    sid: constr(pattern=r'^WH[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Services/{ChatServiceSid}/Conversations/{ConversationSid}/Webhooks/{Sid}',
    description=""" Update an existing conversation-scoped webhook """,
    tags=['conversation_management', 'participant_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def update_service_conversation_scoped_webhook(
    chat_service_sid: constr(
        pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='ChatServiceSid'),
    conversation_sid: str = Path(..., alias='ConversationSid'),
    sid: constr(pattern=r'^WH[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/v1/Services/{ChatServiceSid}/Conversations/{Sid}',
    description=""" Remove a conversation from your service """,
    tags=['conversation_management', 'scoped_webhook_operations'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def delete_service_conversation(
    chat_service_sid: constr(
        pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='ChatServiceSid'),
    sid: str = Path(..., alias='Sid'),
    x__twilio__webhook__enabled: Optional[
        ServiceConversationEnumWebhookEnabledType
    ] = Header(None, alias='X-Twilio-Webhook-Enabled'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Services/{ChatServiceSid}/Conversations/{Sid}',
    description=""" Fetch a conversation from your service """,
    tags=['conversation_management', 'participant_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_service_conversation(
    chat_service_sid: constr(
        pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='ChatServiceSid'),
    sid: str = Path(..., alias='Sid'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Services/{ChatServiceSid}/Conversations/{Sid}',
    description=""" Update an existing conversation in your service """,
    tags=[
        'conversation_management',
        'service_configuration',
        'scoped_webhook_operations',
    ],
    security=[
        HTTPBasic(name="None"),
    ],
)
def update_service_conversation(
    chat_service_sid: constr(
        pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='ChatServiceSid'),
    sid: str = Path(..., alias='Sid'),
    x__twilio__webhook__enabled: Optional[
        ServiceConversationEnumWebhookEnabledType
    ] = Header(None, alias='X-Twilio-Webhook-Enabled'),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Services/{ChatServiceSid}/ParticipantConversations',
    description=""" Retrieve a list of all Conversations that this Participant belongs to by identity or by address. Only one parameter should be specified. """,
    tags=['participant_management', 'user_conversation_relationship'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def list_service_participant_conversation(
    chat_service_sid: constr(
        pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='ChatServiceSid'),
    identity: Optional[str] = Query(None, alias='Identity'),
    address: Optional[str] = Query(None, alias='Address'),
    page_size: Optional[conint(ge=1, le=1000)] = Query(None, alias='PageSize'),
    page: Optional[conint(ge=0)] = Query(None, alias='Page'),
    page_token: Optional[str] = Query(None, alias='PageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Services/{ChatServiceSid}/Roles',
    description=""" Retrieve a list of all user roles in your service """,
    tags=['conversation_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def list_service_role(
    chat_service_sid: constr(
        pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='ChatServiceSid'),
    page_size: Optional[conint(ge=1, le=1000)] = Query(None, alias='PageSize'),
    page: Optional[conint(ge=0)] = Query(None, alias='Page'),
    page_token: Optional[str] = Query(None, alias='PageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Services/{ChatServiceSid}/Roles',
    description=""" Create a new user role in your service """,
    tags=[
        'configuration_management',
        'conversation_management',
        'role_configuration',
        'service_configuration',
    ],
    security=[
        HTTPBasic(name="None"),
    ],
)
def create_service_role(
    chat_service_sid: constr(
        pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='ChatServiceSid'),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/v1/Services/{ChatServiceSid}/Roles/{Sid}',
    description=""" Remove a user role from your service """,
    tags=['conversation_management', 'participant_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def delete_service_role(
    chat_service_sid: constr(
        pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='ChatServiceSid'),
    sid: constr(pattern=r'^RL[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Services/{ChatServiceSid}/Roles/{Sid}',
    description=""" Fetch a user role from your service """,
    tags=['conversation_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_service_role(
    chat_service_sid: constr(
        pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='ChatServiceSid'),
    sid: constr(pattern=r'^RL[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Services/{ChatServiceSid}/Roles/{Sid}',
    description=""" Update an existing user role in your service """,
    tags=['service_configuration'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def update_service_role(
    chat_service_sid: constr(
        pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='ChatServiceSid'),
    sid: constr(pattern=r'^RL[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Services/{ChatServiceSid}/Users',
    description=""" Retrieve a list of all conversation users in your service """,
    tags=[
        'conversation_management',
        'participant_management',
        'user_conversation_relationship',
    ],
    security=[
        HTTPBasic(name="None"),
    ],
)
def list_service_user(
    chat_service_sid: constr(
        pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='ChatServiceSid'),
    page_size: Optional[conint(ge=1, le=1000)] = Query(None, alias='PageSize'),
    page: Optional[conint(ge=0)] = Query(None, alias='Page'),
    page_token: Optional[str] = Query(None, alias='PageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Services/{ChatServiceSid}/Users',
    description=""" Add a new conversation user to your service """,
    tags=['configuration_management', 'scoped_webhook_operations'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def create_service_user(
    chat_service_sid: constr(
        pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='ChatServiceSid'),
    x__twilio__webhook__enabled: Optional[ServiceUserEnumWebhookEnabledType] = Header(
        None, alias='X-Twilio-Webhook-Enabled'
    ),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/v1/Services/{ChatServiceSid}/Users/{Sid}',
    description=""" Remove a conversation user from your service """,
    tags=['configuration_management', 'scoped_webhook_operations'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def delete_service_user(
    chat_service_sid: constr(
        pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='ChatServiceSid'),
    sid: str = Path(..., alias='Sid'),
    x__twilio__webhook__enabled: Optional[ServiceUserEnumWebhookEnabledType] = Header(
        None, alias='X-Twilio-Webhook-Enabled'
    ),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Services/{ChatServiceSid}/Users/{Sid}',
    description=""" Fetch a conversation user from your service """,
    tags=['service_configuration'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_service_user(
    chat_service_sid: constr(
        pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='ChatServiceSid'),
    sid: str = Path(..., alias='Sid'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Services/{ChatServiceSid}/Users/{Sid}',
    description=""" Update an existing conversation user in your service """,
    tags=[
        'configuration_management',
        'service_configuration',
        'scoped_webhook_operations',
    ],
    security=[
        HTTPBasic(name="None"),
    ],
)
def update_service_user(
    chat_service_sid: constr(
        pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='ChatServiceSid'),
    sid: str = Path(..., alias='Sid'),
    x__twilio__webhook__enabled: Optional[ServiceUserEnumWebhookEnabledType] = Header(
        None, alias='X-Twilio-Webhook-Enabled'
    ),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Services/{ChatServiceSid}/Users/{UserSid}/Conversations',
    description=""" Retrieve a list of all User Conversations for the User. """,
    tags=['user_conversation_relationship'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def list_service_user_conversation(
    chat_service_sid: constr(
        pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='ChatServiceSid'),
    user_sid: str = Path(..., alias='UserSid'),
    page_size: Optional[conint(ge=1, le=1000)] = Query(None, alias='PageSize'),
    page: Optional[conint(ge=0)] = Query(None, alias='Page'),
    page_token: Optional[str] = Query(None, alias='PageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/v1/Services/{ChatServiceSid}/Users/{UserSid}/Conversations/{ConversationSid}',
    description=""" Delete a specific User Conversation. """,
    tags=['user_conversation_relationship', 'participant_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def delete_service_user_conversation(
    chat_service_sid: constr(
        pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='ChatServiceSid'),
    user_sid: str = Path(..., alias='UserSid'),
    conversation_sid: str = Path(..., alias='ConversationSid'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Services/{ChatServiceSid}/Users/{UserSid}/Conversations/{ConversationSid}',
    description=""" Fetch a specific User Conversation. """,
    tags=[
        'conversation_management',
        'participant_management',
        'user_conversation_relationship',
    ],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_service_user_conversation(
    chat_service_sid: constr(
        pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='ChatServiceSid'),
    user_sid: str = Path(..., alias='UserSid'),
    conversation_sid: str = Path(..., alias='ConversationSid'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Services/{ChatServiceSid}/Users/{UserSid}/Conversations/{ConversationSid}',
    description=""" Update a specific User Conversation. """,
    tags=[
        'conversation_management',
        'participant_management',
        'user_conversation_relationship',
    ],
    security=[
        HTTPBasic(name="None"),
    ],
)
def update_service_user_conversation(
    chat_service_sid: constr(
        pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34
    ) = Path(..., alias='ChatServiceSid'),
    user_sid: str = Path(..., alias='UserSid'),
    conversation_sid: str = Path(..., alias='ConversationSid'),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/v1/Services/{Sid}',
    description=""" Remove a conversation service with all its nested resources from your account """,
    tags=['role_configuration'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def delete_service(
    sid: constr(pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    )
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Services/{Sid}',
    description=""" Fetch a conversation service from your account """,
    tags=['role_configuration'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_service(
    sid: constr(pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    )
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Users',
    description=""" Retrieve a list of all conversation users in your account's default service """,
    tags=['user_account_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def list_user(
    page_size: Optional[conint(ge=1, le=1000)] = Query(None, alias='PageSize'),
    page: Optional[conint(ge=0)] = Query(None, alias='Page'),
    page_token: Optional[str] = Query(None, alias='PageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Users',
    description=""" Add a new conversation user to your account's default service """,
    tags=['configuration_management', 'scoped_webhook_operations'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def create_user(
    x__twilio__webhook__enabled: Optional[UserEnumWebhookEnabledType] = Header(
        None, alias='X-Twilio-Webhook-Enabled'
    ),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/v1/Users/{Sid}',
    description=""" Remove a conversation user from your account's default service """,
    tags=['configuration_management', 'scoped_webhook_operations'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def delete_user(
    sid: str = Path(..., alias='Sid'),
    x__twilio__webhook__enabled: Optional[UserEnumWebhookEnabledType] = Header(
        None, alias='X-Twilio-Webhook-Enabled'
    ),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Users/{Sid}',
    description=""" Fetch a conversation user from your account's default service """,
    tags=['configuration_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_user(sid: str = Path(..., alias='Sid')):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Users/{Sid}',
    description=""" Update an existing conversation user in your account's default service """,
    tags=['configuration_management', 'scoped_webhook_operations'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def update_user(
    sid: str = Path(..., alias='Sid'),
    x__twilio__webhook__enabled: Optional[UserEnumWebhookEnabledType] = Header(
        None, alias='X-Twilio-Webhook-Enabled'
    ),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Users/{UserSid}/Conversations',
    description=""" Retrieve a list of all User Conversations for the User. """,
    tags=['user_conversation_relationship'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def list_user_conversation(
    user_sid: str = Path(..., alias='UserSid'),
    page_size: Optional[conint(ge=1, le=1000)] = Query(None, alias='PageSize'),
    page: Optional[conint(ge=0)] = Query(None, alias='Page'),
    page_token: Optional[str] = Query(None, alias='PageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/v1/Users/{UserSid}/Conversations/{ConversationSid}',
    description=""" Delete a specific User Conversation. """,
    tags=['user_conversation_relationship', 'conversation_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def delete_user_conversation(
    user_sid: str = Path(..., alias='UserSid'),
    conversation_sid: str = Path(..., alias='ConversationSid'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Users/{UserSid}/Conversations/{ConversationSid}',
    description=""" Fetch a specific User Conversation. """,
    tags=['user_conversation_relationship', 'conversation_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_user_conversation(
    user_sid: str = Path(..., alias='UserSid'),
    conversation_sid: str = Path(..., alias='ConversationSid'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Users/{UserSid}/Conversations/{ConversationSid}',
    description=""" Update a specific User Conversation. """,
    tags=['user_conversation_relationship', 'conversation_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def update_user_conversation(
    user_sid: str = Path(..., alias='UserSid'),
    conversation_sid: str = Path(..., alias='ConversationSid'),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
